### ISSUE TITLE
Providing `policy_arn_count` is redundant.

### ISSUE THREAD

**Issue by TimJones** [QuiNovas/terraform-aws-user-role#4]
Since the v0.12 update, providing `policy_arn_count` alongside `policy_arns` as a list since is can be extrapolated with `length(var.poliy_arns)`. Doing it this way also mitigates user error in the case of a mismatch between `policy_arn_count` and the actual count of items in `policy_arns`.

**Comment by vchinnakotla** [comment]
Thanks for the suggestion. It has been pushed in the latest release.
